export interface ApiResponse<T = any> {
  data: T | null;
  error: string | null;
  details?: string | null;
  ok: boolean;
  isStarting?: boolean;
  rateLimited?: boolean;
}

export const safeFetchJson = async (res: Response): Promise<ApiResponse> => {
  try {
    const text = await res.text();
    if (!text) {
      if (res.status === 403) return { data: null, error: "Access denied. Insufficient permissions for this role.", ok: false };
      return { data: null, error: null, ok: res.ok };
    }
    
    // Check for platform warmup/system messages
    if (text.includes("<title>Starting Server...</title>") || text.includes("Please wait while your application starts...")) {
      return { data: null, error: "Application is starting. Please wait...", ok: false, isStarting: true };
    }

    if (text.includes("Rate exceeded") || text.includes("RESOURCE_EXHAUSTED")) {
      return { data: null, error: "Rate limit exceeded. Please wait.", ok: false, rateLimited: true };
    }

    if (!res.ok) {
      try {
        const data = JSON.parse(text);
        if (res.status === 401) {
           window.dispatchEvent(new CustomEvent('api:unauthorized'));
        }
        return { 
          data: null, 
          error: data.error || data.message || `Error ${res.status}`, 
          details: data.details || null,
          ok: false 
        };
      } catch (err) {
        // Fallback for HTML/Text responses generated by Nginx/Proxy
        if (res.status === 403) return { data: null, error: "Access denied. Insufficient permissions for this role.", ok: false };
        if (res.status === 401) {
          window.dispatchEvent(new CustomEvent('api:unauthorized'));
          return { data: null, error: "Unauthorized access", ok: false };
        }
        if (res.status === 404) return { data: null, error: "Resource not found", ok: false };
        if (res.status >= 500) return { data: null, error: `Internal server error (${res.status})`, ok: false };
        
        return { data: null, error: `Protocol error (${res.status})`, ok: false };
      }
    }

    // if res.ok is true
    try {
      const data = JSON.parse(text);
      return { data, error: null, ok: true };
    } catch (e) {
      console.warn("API succeeded but response is not JSON. URL:", res.url);
      return { data: text as any, error: null, ok: true };
    }
  } catch (err) {
    return { data: null, error: "Internal communication error", ok: false };
  }
};

export const apiFetch = async (url: string, options: RequestInit = {}, userEmail: string = '', retries = 1, isStartingRetries = 10): Promise<ApiResponse> => {
  const headers = {
    ...(options.body instanceof FormData ? {} : { 'Content-Type': 'application/json' }),
    ...(userEmail ? { 'x-user-email': userEmail } : {}),
    ...(options.headers || {})
  } as Record<string, string>;

  // Only GET requests should be retried automatically for idempotency safety
  const shouldRetry = retries > 0 && (!options.method || options.method.toUpperCase() === 'GET');

  const controller = new AbortController();
  const timeoutId = setTimeout(() => controller.abort(), 15000); // 15 second timeout

  try {
    const res = await fetch(url, { ...options, headers, signal: controller.signal });
    clearTimeout(timeoutId);
    const parsedRes = await safeFetchJson(res);
    
    // Automatically poll if the server is starting up
    if (parsedRes.isStarting && isStartingRetries > 0) {
      console.warn(`Server is starting. Retrying fetch to ${url}... (${isStartingRetries} retries left)`);
      await new Promise(resolve => setTimeout(resolve, 3000)); // wait 3 seconds
      return apiFetch(url, options, userEmail, retries, isStartingRetries - 1);
    }
    
    return parsedRes;
  } catch (err: any) {
    clearTimeout(timeoutId);
    if (err.name === 'AbortError') {
      return { data: null, error: "Request timed out. Please try again.", ok: false };
    }
    if (shouldRetry) {
      console.warn(`Retrying fetch to ${url}...`);
      await new Promise(resolve => setTimeout(resolve, 500)); // wait 500ms before retry
      return apiFetch(url, options, userEmail, retries - 1, isStartingRetries);
    }
    return { data: null, error: "Network error. Check your connection.", ok: false };
  }
};
